name = input("What is your name")
print (name)
age = input("What is your age")
print (age)
color = input("What is your favorite color")
print (color)
print("Hello" + name + ", you are" + age + "years old and your favorite color is")